refactor: remove vite example
candirugame/candiru pull request #108
Opened 2024-10-23 15:23 UTC by IsaacThoman

2024-10-31 02:15 UTC, AustinJMann requested changes
Did you mean to remove the .gitignore?

2024-11-04 16:28 UTC, IsaacThoman commented
> Did you mean to remove the .gitignore?

yes

2024-11-08 04:17 UTC, merged

2024-11-08 05:17 UTC, IsaacThoman commented
:tada: This PR is included in version 1.6.0-beta.13 :tada:

The release is available on [GitHub release](https://github.com/candirugame/candiru/releases/tag/v1.6.0-beta.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-11-08 21:34 UTC, IsaacThoman commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on [GitHub release](https://github.com/candirugame/candiru/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: